cottages.feldweg.register_feldweg("default:dirt_with_grass", "", "cottages_feldweg_edges.png")
cottages.feldweg.register_feldweg("default:gravel", "_gravel")
cottages.feldweg.register_feldweg("default:dirt_with_coniferous_litter", "_coniferous")
cottages.feldweg.register_feldweg("default:dirt_with_snow", "_snow")
cottages.feldweg.register_feldweg("default:dirt_with_dry_grass", "_dry")
